### ISSUE TITLE
What is the section part in manifest.json for?

### ISSUE THREAD

**Issue by svhorstmann** [jcailan/cap-fe-samples#1]
Hi Jhodel,

I am new to Fiori Elements and wonder what the sections part in manifest.json is for:

> "sections": {
>                                     "ToSalesData::com.sap.vocabularies.UI.v1.LineItem": {
>                                         "navigationProperty": "ToSalesData",
>                                         "entitySet": "SalesData",
>                                         "tableSettings": {
>                                             "type": "GridTable"
>                                         }
>                                     }
>                                 }

I tried it in my own project but it seems not to substitute object pages or annotations so I wonder what it is for.

Thanks for any information on that!
Best regards
Svea

**Comment by jcailan** [comment]
Hi @svhorstmann 

This is a configuration of Fiori Element Object Page to make the table in one of the sections use GridTable. By default, Fiori Element Object Page is using ResponsiveTable type.

I hope this answers your question.
